LOCATION_MAPPING = {
    [0xEC00E1] = {"@World/Hall of Hieroglyphs/First Jewel Box"},
	[0xEC00E2] = {"@World/Hall of Hieroglyphs/Second Jewel Box"},
	[0xEC00E3] = {"@World/Hall of Hieroglyphs/Third Jewel Box"},
	[0xEC00E4] = {"@World/Hall of Hieroglyphs/Fourth Jewel Box"},
	[0xEC00E7] = {"@World/Hall of Hieroglyphs/Full Health Item Box"},


	[0xEC0621] = {"@World/Palm Tree Paradise/First Box"},
	[0xEC0641] = {"@World/Palm Tree Paradise/Ledge Box"},
	[0xEC0681] = {"@World/Palm Tree Paradise/Dead End Box"},
	[0xEC0622] = {"@World/Palm Tree Paradise/Box Before Cave"},
	[0xEC06C2] = {"@World/Palm Tree Paradise/Hidden Box"},
	[0xEC06E3] = {"@World/Palm Tree Paradise/Platform Cave Jewel Box"},
	[0xEC06E4] = {"@World/Palm Tree Paradise/Ladder Cave Box"},
	[0xEC06E5] = {"@World/Palm Tree Paradise/CD Box"},
	[0xEC06E7] = {"@World/Palm Tree Paradise/Full Health Item Box"},

	[0xEC07E1] = {"@World/Wildflower Fields/Current Cave Box"},
	[0xEC0722] = {"@World/Wildflower Fields/Sunflower Jewel Box"},
	[0xEC07C2] = {"@World/Wildflower Fields/Sunflower Box"},
	[0xEC0723] = {"@World/Wildflower Fields/Slope Room Box"},
	[0xEC07C3] = {"@World/Wildflower Fields/8-Shaped Cave Box"},
	[0xEC07E4] = {"@World/Wildflower Fields/Beezly Box"},
	[0xEC07E5] = {"@World/Wildflower Fields/CD Box"},
	[0xEC0727] = {"@World/Wildflower Fields/Full Health Item Box"},

	[0xEC0821] = {"@World/Mystic Lake/Air Pocket Box"},
	[0xEC08C1] = {"@World/Mystic Lake/Large Cave Box"},
	[0xEC0822] = {"@World/Mystic Lake/Hill Room Box"},
	[0xEC0842] = {"@World/Mystic Lake/Small Cave Box"},
	[0xEC0882] = {"@World/Mystic Lake/Rock Cave Box"},
	[0xEC0823] = {"@World/Mystic Lake/Cavern Box"},
	[0xEC08C3] = {"@World/Mystic Lake/Spring Cave Box"},
	[0xEC0824] = {"@World/Mystic Lake/Box Before Bridge"},
	[0xEC08C4] = {"@World/Mystic Lake/Lake Exit Bubble Box"},
	[0xEC08E5] = {"@World/Mystic Lake/CD Box"},
	[0xEC08E7] = {"@World/Mystic Lake/Full Health Item Box"},

	[0xEC0921] = {"@World/Monsoon Jungle/Spiky Box"},
	[0xEC0941] = {"@World/Monsoon Jungle/Escape Climb Box"},
	[0xEC0981] = {"@World/Monsoon Jungle/Brown Pipe Cave Box"},
	[0xEC09E2] = {"@World/Monsoon Jungle/Fat Plummet Box"},
	[0xEC0923] = {"@World/Monsoon Jungle/Descent Box"},
	[0xEC09C3] = {"@World/Monsoon Jungle/Puffy Hallway Box"},
	[0xEC09E4] = {"@World/Monsoon Jungle/Buried Cave Box"},
	[0xEC09E5] = {"@World/Monsoon Jungle/CD Box"},
	[0xEC09E7] = {"@World/Monsoon Jungle/Full Health Item Box"},

	[0xEC0AE1] = {"@World/Cractus/0:55"},
	[0xEC0AE2] = {"@World/Cractus/0:35"},
	[0xEC0AE3] = {"@World/Cractus/0:15"},


	[0xEC0C21] = {"@World/The Curious Factory/First Drop Box"},
	[0xEC0CC1] = {"@World/The Curious Factory/Thin Gap Box"},
	[0xEC0C22] = {"@World/The Curious Factory/Early Escape Box"},
	[0xEC0CC2] = {"@World/The Curious Factory/Conveyor Room Box"},
	[0xEC0C23] = {"@World/The Curious Factory/Late Escape Box"},
	[0xEC0CC3] = {"@World/The Curious Factory/Underground Chamber Box"},
	[0xEC0C24] = {"@World/The Curious Factory/Frog Switch Room Box"},
	[0xEC0CC4] = {"@World/The Curious Factory/Gear Elevator Box"},
	[0xEC0CE5] = {"@World/The Curious Factory/CD Box"},

	[0xEC0D21] = {"@World/The Toxic Landfill/Portal Room Box"},
	[0xEC0DC1] = {"@World/The Toxic Landfill/Box Above Portal"},
	[0xEC0DE2] = {"@World/The Toxic Landfill/Fat Room Box"},
	[0xEC0D23] = {"@World/The Toxic Landfill/Spring Room Box"},
	[0xEC0DC3] = {"@World/The Toxic Landfill/Current Circle Box"},
	[0xEC0D24] = {"@World/The Toxic Landfill/Ledge Box"},
	[0xEC0DC4] = {"@World/The Toxic Landfill/Transformation Puzzle Box"},
	[0xEC0DE5] = {"@World/The Toxic Landfill/CD Box"},
	[0xEC0D27] = {"@World/The Toxic Landfill/Full Health Item Box"},

	[0xEC0EE1] = {"@World/40 Below Fridge/Looping Room Box"},
	[0xEC0EE2] = {"@World/40 Below Fridge/Maze Room Box"},
	[0xEC0EE3] = {"@World/40 Below Fridge/Snowman Puzzle Upper Box"},
	[0xEC0EE4] = {"@World/40 Below Fridge/Snowman Puzzle Lower Box"},
	[0xEC0EE5] = {"@World/40 Below Fridge/CD Box"},

	[0xEC0F61] = {"@World/Pinball Zone/Rolling Room Box"},
	[0xEC0F81] = {"@World/Pinball Zone/Switch Room Box"},
	[0xEC0FE2] = {"@World/Pinball Zone/Fruit Room Box"},
	[0xEC0FE3] = {"@World/Pinball Zone/Jungle Room Box"},
	[0xEC0FE4] = {"@World/Pinball Zone/Snow Room Box"},
	[0xEC0FE5] = {"@World/Pinball Zone/CD Box"},
	[0xEC0F67] = {"@World/Pinball Zone/Full Health Item Box"},
	[0xEC0F87] = {"@World/Pinball Zone/Pink Room Full Health Item Box"},
	[0xEC0F88] = {"@World/Pinball Zone/Rolling Room Full Health Item Box"},

	[0xEC10E1] = {"@World/Cuckoo Condor/0:55"},
	[0xEC10E2] = {"@World/Cuckoo Condor/0:35"},
	[0xEC10E3] = {"@World/Cuckoo Condor/0:15"},


	[0xEC1261] = {"@World/Toy Block Tower/Toy Car Overhang Box"},
	[0xEC1281] = {"@World/Toy Block Tower/Tower Exterior Top Box"},
	[0xEC1222] = {"@World/Toy Block Tower/Hidden Tower Room Box"},
	[0xEC12C2] = {"@World/Toy Block Tower/Digging Room Box"},
	[0xEC1223] = {"@World/Toy Block Tower/Fire Box"},
	[0xEC1243] = {"@World/Toy Block Tower/Hidden Falling Block Door Box"},
	[0xEC1283] = {"@World/Toy Block Tower/Bonfire Block Box"},
	[0xEC1224] = {"@World/Toy Block Tower/Red Pipe Box"},
	[0xEC12C4] = {"@World/Toy Block Tower/Escape Ledge Box"},
	[0xEC12E5] = {"@World/Toy Block Tower/CD Box"},
	[0xEC1267] = {"@World/Toy Block Tower/Full Health Item Box"},

	[0xEC1321] = {"@World/The Big Board/First Box"},
	[0xEC13C1] = {"@World/The Big Board/Hard Fire Room Box"},
	[0xEC1322] = {"@World/The Big Board/Normal Fire Room Box"},
	[0xEC13C2] = {"@World/The Big Board/Hard Enemy Room Box"},
	[0xEC1323] = {"@World/The Big Board/Normal Enemy Room Box"},
	[0xEC13C3] = {"@World/The Big Board/Fat Room Box"},
	[0xEC1324] = {"@World/The Big Board/Toy Car Box"},
	[0xEC13C4] = {"@World/The Big Board/Flat Room Box"},
	[0xEC13E5] = {"@World/The Big Board/CD Box"},
	[0xEC1367] = {"@World/The Big Board/Full Health Item Box"},

	[0xEC1421] = {"@World/Doodle Woods/Box Behind Wall"},
	[0xEC14C1] = {"@World/Doodle Woods/Grey Square Box"},
	[0xEC1422] = {"@World/Doodle Woods/Orange Escape Box"},
	[0xEC14C2] = {"@World/Doodle Woods/Pink Circle Box"},
	[0xEC1423] = {"@World/Doodle Woods/Buried Door Box"},
	[0xEC14C3] = {"@World/Doodle Woods/Purple Square Box"},
	[0xEC1424] = {"@World/Doodle Woods/Blue Escape Box"},
	[0xEC14C4] = {"@World/Doodle Woods/Blue Circle Box"},
	[0xEC14E5] = {"@World/Doodle Woods/CD Box"},

	[0xEC15E1] = {"@World/Domino Row/Racing Box"},
	[0xEC15E2] = {"@World/Domino Row/Rolling Box"},
	[0xEC1563] = {"@World/Domino Row/Swimming Detour Box"},
	[0xEC1583] = {"@World/Domino Row/Swimming Room Escape Box"},
	[0xEC15E4] = {"@World/Domino Row/Keyzer Room Box"},
	[0xEC15E5] = {"@World/Domino Row/CD Box"},

	[0xEC16E1] = {"@World/Aerodent/0:55"},
	[0xEC16E2] = {"@World/Aerodent/0:35"},
	[0xEC16E3] = {"@World/Aerodent/0:15"},


	[0xEC1821] = {"@World/Crescent Moon Village/Agile Bat Box"},
	[0xEC18C1] = {"@World/Crescent Moon Village/Agile Bat Hidden Box"},
	[0xEC1822] = {"@World/Crescent Moon Village/Metal Platform Box"},
	[0xEC18C2] = {"@World/Crescent Moon Village/Metal Platform Rolling Box"},
	[0xEC1823] = {"@World/Crescent Moon Village/Rolling Box"},
	[0xEC18C3] = {"@World/Crescent Moon Village/!-Switch Rolling Box"},
	[0xEC18E4] = {"@World/Crescent Moon Village/Sewer Box"},
	[0xEC18E5] = {"@World/Crescent Moon Village/CD Box"},

	[0xEC19E1] = {"@World/Arabian Night/Onomi Box"},
	[0xEC1922] = {"@World/Arabian Night/Flying Carpet Overhang Box"},
	[0xEC19C2] = {"@World/Arabian Night/Flying Carpet Dash Attack Box"},
	[0xEC1923] = {"@World/Arabian Night/Zombie Plummet Box"},
	[0xEC19C3] = {"@World/Arabian Night/Kool-Aid Box"},
	[0xEC19E4] = {"@World/Arabian Night/Sewer Box"},
	[0xEC19E5] = {"@World/Arabian Night/CD Box"},

	[0xEC1A21] = {"@World/Fiery Cavern/Lava Dodging Box"},
	[0xEC1AC1] = {"@World/Fiery Cavern/Ice Beyond Door Box"},
	[0xEC1AE2] = {"@World/Fiery Cavern/Long Lava Geyser Box"},
	[0xEC1AE3] = {"@World/Fiery Cavern/Ice Detour Box"},
	[0xEC1AE4] = {"@World/Fiery Cavern/Snowman Box"},
	[0xEC1AE5] = {"@World/Fiery Cavern/CD Box"},

	[0xEC1B21] = {"@World/Hotel Horror/1F Hallway Box"},
	[0xEC1BC1] = {"@World/Hotel Horror/Room 102 Box"},
	[0xEC1B22] = {"@World/Hotel Horror/2F Hallway Box"},
	[0xEC1BC2] = {"@World/Hotel Horror/Room 303 Box"},
	[0xEC1B23] = {"@World/Hotel Horror/3F Hallway Box"},
	[0xEC1BC3] = {"@World/Hotel Horror/Room 402 Box"},
	[0xEC1B24] = {"@World/Hotel Horror/4F Hallway Box"},
	[0xEC1BC4] = {"@World/Hotel Horror/Exterior Box"},
	[0xEC1BE5] = {"@World/Hotel Horror/CD Box"},

	[0xEC1CE1] = {"@World/Catbat/0:55"},
	[0xEC1CE2] = {"@World/Catbat/0:35"},
	[0xEC1CE3] = {"@World/Catbat/0:15"},


	[0xEC1EE1] = {"@World/Golden Passage/Current Puzzle Box"},
	[0xEC1EE2] = {"@World/Golden Passage/River Box"},
	[0xEC1EE3] = {"@World/Golden Passage/Bat Room Box"},
	[0xEC1EE4] = {"@World/Golden Passage/Mad Scienstein Box"},
}
