LOCATION_MAPPING = {
    [0xEC00] = {"@World/Hall of Hieroglyphs/First Jewel Box"},
	[0xEC01] = {"@World/Hall of Hieroglyphs/Second Jewel Box"},
	[0xEC02] = {"@World/Hall of Hieroglyphs/Third Jewel Box"},
	[0xEC03] = {"@World/Hall of Hieroglyphs/Fourth Jewel Box"},
	[0xEC04] = {"@World/Hall of Hieroglyphs/Full Health Item Box"},

	[0xEC05] = {"@World/Spoiled Rotten/Defeat Spoiled Rotten"},

	[0xEC06] = {"@World/Palm Tree Paradise/First Box"},
	[0xEC07] = {"@World/Palm Tree Paradise/Ledge Box"},
	[0xEC08] = {"@World/Palm Tree Paradise/Dead End Box"},
	[0xEC09] = {"@World/Palm Tree Paradise/Box Before Cave"},
	[0xEC0A] = {"@World/Palm Tree Paradise/Hidden Box"},
	[0xEC0B] = {"@World/Palm Tree Paradise/Platform Cave Jewel Box"},
	[0xEC0C] = {"@World/Palm Tree Paradise/Ladder Cave Box"},
	[0xEC0D] = {"@World/Palm Tree Paradise/CD Box"},
	[0xEC0E] = {"@World/Palm Tree Paradise/Full Health Item Box"},
	
	[0xEC0F] = {"@World/Wildflower Fields/Current Cave Box"},
	[0xEC10] = {"@World/Wildflower Fields/Sunflower Jewel Box"},
	[0xEC11] = {"@World/Wildflower Fields/Sunflower Box"},
	[0xEC12] = {"@World/Wildflower Fields/Slope Room Box"},
	[0xEC13] = {"@World/Wildflower Fields/8-Shaped Cave Box Box"},
	[0xEC14] = {"@World/Wildflower Fields/Beezly Box"},
	[0xEC15] = {"@World/Wildflower Fields/CD Box"},
	[0xEC16] = {"@World/Wildflower Fields/Full Health Item Box"},
	
	[0xEC17] = {"@World/Mystic Lake/Air Pocket Box"},
	[0xEC18] = {"@World/Mystic Lake/Large Cave Box"},
	[0xEC19] = {"@World/Mystic Lake/Hill Room Box"},
	[0xEC1A] = {"@World/Mystic Lake/Small Cave Box"},
	[0xEC1B] = {"@World/Mystic Lake/Cavern Box"},
	[0xEC1C] = {"@World/Mystic Lake/Spring Cave Box"},
	[0xEC1D] = {"@World/Mystic Lake/Box Before Bridge"},
	[0xEC1E] = {"@World/Mystic Lake/Lake Exit Bubble Box"},
	[0xEC1F] = {"@World/Mystic Lake/CD Box"},
	[0xEC20] = {"@World/Mystic Lake/Full Health Item Box"},
	
	[0xEC21] = {"@World/Monsoon Jungle/Spiky Box"},
	[0xEC22] = {"@World/Monsoon Jungle/Escape Climb Box"},
	[0xEC23] = {"@World/Monsoon Jungle/Brown Pipe Cave Box"},
	[0xEC24] = {"@World/Monsoon Jungle/Fat Plummet Box"},	
	[0xEC25] = {"@World/Monsoon Jungle/Descent Box"},
	[0xEC26] = {"@World/Monsoon Jungle/Puffy Hallway Box"},	
	[0xEC27] = {"@World/Monsoon Jungle/Buried Cave Box"},
	[0xEC28] = {"@World/Monsoon Jungle/CD Box"},	
	[0xEC29] = {"@World/Monsoon Jungle/Full Health Item Box"},
	
	[0xEC2A] = {"@World/Cractus/Defeat Cractus"},	
	
	[0xEC2B] = {"@World/The Curious Factory/First Drop Box"},
	[0xEC2C] = {"@World/The Curious Factory/Thin Gap Box"},
	[0xEC2D] = {"@World/The Curious Factory/Early Escape Box"},
	[0xEC2E] = {"@World/The Curious Factory/Conveyor Room Box"},
	[0xEC2F] = {"@World/The Curious Factory/Late Escape Box"},
	[0xEC30] = {"@World/The Curious Factory/Underground Chamber Box"},
	[0xEC31] = {"@World/The Curious Factory/Frog Switch Room Box"},
	[0xEC32] = {"@World/The Curious Factory/Gear Elevator Box"},
	[0xEC33] = {"@World/The Curious Factory/CD Box"},
	
	[0xEC34] = {"@World/The Toxic Landfill/Portal Room Box"},
	[0xEC35] = {"@World/The Toxic Landfill/Box Above Portal"},
	[0xEC36] = {"@World/The Toxic Landfill/Fat Room Box"},
	[0xEC37] = {"@World/The Toxic Landfill/Spring Room Box"},
	[0xEC38] = {"@World/The Toxic Landfill/Current Circle Box"},
	[0xEC39] = {"@World/The Toxic Landfill/Ledge Box"},
	[0xEC3A] = {"@World/The Toxic Landfill/Transformation Puzzle Box"},
	[0xEC3B] = {"@World/The Toxic Landfill/CD Box"},
	[0xEC3C] = {"@World/The Toxic Landfill/Full Health Item Box"},
	
	[0xEC3D] = {"@World/40 Below Fridge/Looping Room Box"},
	[0xEC3E] = {"@World/40 Below Fridge/Maze Room Box"},
	[0xEC3F] = {"@World/40 Below Fridge/Snowman Puzzle Upper Box"},
	[0xEC40] = {"@World/40 Below Fridge/Snowman Puzzle Lower Box"},
	[0xEC41] = {"@World/40 Below Fridge/CD Box"},	
	
	[0xEC42] = {"@World/Pinball Zone/Rolling Room Box"},
	[0xEC43] = {"@World/Pinball Zone/Switch Room Box"},
	[0xEC44] = {"@World/Pinball Zone/Fruit Room Box"},
	[0xEC45] = {"@World/Pinball Zone/Jungle Room Box"},
	[0xEC46] = {"@World/Pinball Zone/Snow Room Box"},	
	[0xEC47] = {"@World/Pinball Zone/CD Box"},
	[0xEC48] = {"@World/Pinball Zone/Full Health Item Box"},

	[0xEC49] = {"@World/Cuckoo Condor/Defeat Cuckoo Condor"},
	
	[0xEC4A] = {"@World/Toy Block Tower/Toy Car Overhang Box"},
	[0xEC4B] = {"@World/Toy Block Tower/Tower Exterior Top Box"},
	[0xEC4C] = {"@World/Toy Block Tower/Hidden Tower Room Box"},
	[0xEC4D] = {"@World/Toy Block Tower/Digging Room Box"},
	[0xEC4E] = {"@World/Toy Block Tower/Fire Box"},
	[0xEC4F] = {"@World/Toy Block Tower/Hidden Falling Block Door Box"},
	[0xEC50] = {"@World/Toy Block Tower/Bonfire Block Box"},
	[0xEC51] = {"@World/Toy Block Tower/Red Pipe Box"},
	[0xEC52] = {"@World/Toy Block Tower/Escape Ledge Box"},	
	[0xEC53] = {"@World/Toy Block Tower/CD Box"},	
	[0xEC54] = {"@World/Toy Block Tower/Full Health Item Box"},
	
	[0xEC55] = {"@World/The Big Board/First Box"},
	[0xEC56] = {"@World/The Big Board/Hard Fire Room Box"},
	[0xEC57] = {"@World/The Big Board/Normal Fire Room Box"},
	[0xEC58] = {"@World/The Big Board/Hard Enemy Room Box"},
	[0xEC59] = {"@World/The Big Board/Normal Enemy Room Box"},
	[0xEC5A] = {"@World/The Big Board/Fat Room Box"},
	[0xEC5B] = {"@World/The Big Board/Toy Car Box"},
	[0xEC5C] = {"@World/The Big Board/Flat Room Box"},	
	[0xEC5D] = {"@World/The Big Board/CD Box"},	
	[0xEC5E] = {"@World/The Big Board/Full Health Item Box"},
	
	[0xEC5F] = {"@World/Doodle Woods/Box Behind Wall"},
	[0xEC60] = {"@World/Doodle Woods/Grey Square Box"},
	[0xEC61] = {"@World/Doodle Woods/Orange Escape Box"},
	[0xEC62] = {"@World/Doodle Woods/Pink Circle Box"},
	[0xEC63] = {"@World/Doodle Woods/Buried Door Box"},
	[0xEC64] = {"@World/Doodle Woods/Purple Square Box"},
	[0xEC65] = {"@World/Doodle Woods/Blue Escape Box"},
	[0xEC66] = {"@World/Doodle Woods/Blue Circle Box"},	
	[0xEC67] = {"@World/Doodle Woods/CD Box"},
	
	[0xEC68] = {"@World/Domino Row/Racing Box"},
	[0xEC69] = {"@World/Domino Row/Rolling Box"},
	[0xEC6A] = {"@World/Domino Row/Swimming Detour Box"},
	[0xEC6B] = {"@World/Domino Row/Swimming Room Escape Box"},
	[0xEC6C] = {"@World/Domino Row/Keyzer Room Box"},	
	[0xEC6D] = {"@World/Domino Row/CD Box"},
	
	[0xEC6E] = {"@World/Aerodent/Defeat Aerodent"},	

	[0xEC6F] = {"@World/Crescent Moon Village/Agile Bat Box"},
	[0xEC70] = {"@World/Crescent Moon Village/Agile Bat Hidden Box"},
	[0xEC71] = {"@World/Crescent Moon Village/Metal Platform Box"},
	[0xEC72] = {"@World/Crescent Moon Village/Metal Platform Rolling Box"},
	[0xEC73] = {"@World/Crescent Moon Village/Rolling Box"},
	[0xEC74] = {"@World/Crescent Moon Village/!-Switch Rolling Box"},
	[0xEC75] = {"@World/Crescent Moon Village/Sewer Box"},	
	[0xEC76] = {"@World/Crescent Moon Village/CD Box"},
	
	[0xEC77] = {"@World/Arabian Night/Onomi Box"},
	[0xEC78] = {"@World/Arabian Night/Flying Carpet Overhang Box"},
	[0xEC79] = {"@World/Arabian Night/Flying Carpet Dash Attack Box"},
	[0xEC7A] = {"@World/Arabian Night/Zombie Plummet Box"},
	[0xEC7B] = {"@World/Arabian Night/Kool-Aid Box"},
	[0xEC7C] = {"@World/Arabian Night/Sewer Box"},	
	[0xEC7D] = {"@World/Arabian Night/CD Box"},

	[0xEC7E] = {"@World/Fiery Cavern/Lava Dodging Box"},
	[0xEC7F] = {"@World/Fiery Cavern/Ice Beyond Door Box"},
	[0xEC80] = {"@World/Fiery Cavern/Long Lava Geyser Box"},
	[0xEC81] = {"@World/Fiery Cavern/Ice Detour Box"},
	[0xEC82] = {"@World/Fiery Cavern/Snowman Box"},	
	[0xEC83] = {"@World/Fiery Cavern/CD Box"},

	[0xEC84] = {"@World/Hotel Horror/1F Hallway Box"},
	[0xEC85] = {"@World/Hotel Horror/Room 102 Box"},
	[0xEC86] = {"@World/Hotel Horror/2F Hallway Box"},
	[0xEC87] = {"@World/Hotel Horror/Room 303 Box"},
	[0xEC88] = {"@World/Hotel Horror/3F Hallway Box"},
	[0xEC89] = {"@World/Hotel Horror/Room 402 Box"},
	[0xEC8A] = {"@World/Hotel Horror/4F Hallway Box"},	
	[0xEC8B] = {"@World/Hotel Horror/Exterior Box"},	
	[0xEC8C] = {"@World/Hotel Horror/CD Box"},
	
	[0xEC8D] = {"@World/Catbat/Defeat Catbat"},

	[0xEC8E] = {"@World/Golden Passage/Current Puzzle Box"},
	[0xEC8F] = {"@World/Golden Passage/River Box"},
	[0xEC90] = {"@World/Golden Passage/Bat Room Box"},
	[0xEC91] = {"@World/Golden Passage/Mad Scienstein Box"},

	[0xEC92] = {"@World/Golden Diva/Defeat Golden Diva"}
	
	}
	