ROOM_FLAG_MAPPING = {
    [0xFFFFFF] = {[0] = {"Overview"}},
    [0x000000] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Portal Room"}},
    [0x00000B] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Pipe Entrances"}},
    [0x00000C] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Pipe Room"}},
    [0x000001] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Jewel Box 1"}},
    [0x000002] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Shoulder Bash Tutorial"}},
    [0x000003] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Jewel Box 2"}},
    [0x000004] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Dash Attack Tutorial"}},
    [0x000005] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Hallway After Dash"}},
    [0x000006] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Grab And Throw Tutorial"}},
    [0x000007] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Jewel Box 3"}},
    [0x000008] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Keyzer Room"}},
    [0x000009] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Jewel Box 4"}},
    [0x00000A] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Ground Pound Tutorial"}},
    [0x000500] = {[0] = {"Level Views", "Entry/Golden Passage", "Spoiled Rotten"}},
    [0x000501] = {[0] = {"Level Views", "Entry/Golden Passage", "Spoiled Rotten"}},
    [0x010000] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Portal"}},
    [0x010001] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "The Lost Room"}},
    [0x010002] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Outdoors 2"}},
    [0x010003] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Outdoors 3"}},
    [0x010004] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Big Cave"}},
    [0x010005] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Outdoors 4"}},
    [0x010006] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Frog Switch"}},
    [0x010007] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Ladder Cave"}},
    [0x010008] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Underground Cave"}},
    [0x010009] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Outdoors 1"}},
    [0x01000A] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Puzzle Room A"}},
    [0x01000B] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Puzzle Room B"}},
}