ROOM_FLAG_MAPPING = {
    [0xFFFFFF] = {[0] = {"Overview"}},
    [0x000000] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Portal Room"}},
    [0x00000B] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Pipe Entrances"}},
    [0x00000C] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Pipe Room"}},
    [0x000001] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Jewel Box 1"}},
    [0x000002] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Shoulder Bash Tutorial"}},
    [0x000003] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Jewel Box 2"}},
    [0x000004] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Dash Attack Tutorial"}},
    [0x000005] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Hallway After Dash"}},
    [0x000006] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Grab and Throw Tutorial"}},
    [0x000007] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Jewel Box 3"}},
    [0x000008] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Keyzer Room"}},
    [0x000009] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Jewel Box 4"}},
    [0x00000A] = {[0] = {"Level Views", "Entry/Golden Passage", "Hall Of Heiroglyphs", "Ground Pound Tutorial"}},
    [0x000400] = {[0] = {"Level Views", "Entry/Golden Passage", "Spoiled Rotten"}},
    [0x000401] = {[0] = {"Level Views", "Entry/Golden Passage", "Spoiled Rotten"}},
    [0x010000] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Portal"}},
    [0x010001] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "The Lost Room"}},
    [0x010002] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Outdoors 2"}},
    [0x010003] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Outdoors 3"}},
    [0x010004] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Big Cave"}},
    [0x010005] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Outdoors 4"}},
    [0x010006] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Frog Switch"}},
    [0x010007] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Ladder Cave"}},
    [0x010008] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Underground Cave"}},
    [0x010009] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Outdoors 1"}},
    [0x01000A] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Puzzle Room A"}},
    [0x01000B] = {[0] = {"Level Views", "Emerald Passage", "Palm Tree Paradise", "Puzzle Room B"}},
    [0x010100] = {[0] = {"Level Views", "Emerald Passage", "Wildflower Fields", "Portal"}},
    [0x010101] = {[0] = {"Level Views", "Emerald Passage", "Wildflower Fields", "Sky Above Portal"}},
    [0x010102] = {[0] = {"Level Views", "Emerald Passage", "Wildflower Fields", "Outdoors 1"}},
    [0x010103] = {[0] = {"Level Views", "Emerald Passage", "Wildflower Fields", "Bee Sting Escape Sky Puzzle"}},
    [0x010104] = {[0] = {"Level Views", "Emerald Passage", "Wildflower Fields", "Underground Cave"}},
    [0x010105] = {[0] = {"Level Views", "Emerald Passage", "Wildflower Fields", "Sunflower Stem Bottom"}},
    [0x010106] = {[0] = {"Level Views", "Emerald Passage", "Wildflower Fields", "Sunflower Underground Roots"}},
    [0x010107] = {[0] = {"Level Views", "Emerald Passage", "Wildflower Fields", "Water Currents"}},
    [0x010108] = {[0] = {"Level Views", "Emerald Passage", "Wildflower Fields", "Sunflower Top"}},
    [0x010109] = {[0] = {"Level Views", "Emerald Passage", "Wildflower Fields", "Outdoors 2"}},
    [0x01010A] = {[0] = {"Level Views", "Emerald Passage", "Wildflower Fields", "Frog Switch"}},
    [0x01010B] = {[0] = {"Level Views", "Emerald Passage", "Wildflower Fields", "Inside Stem"}},
    [0x01010C] = {[0] = {"Level Views", "Emerald Passage", "Wildflower Fields", "Puzzle Room A"}},
    [0x01010D] = {[0] = {"Level Views", "Emerald Passage", "Wildflower Fields", "Puzzle Room B"}},
    [0x010200] = {[0] = {"Level Views", "Emerald Passage", "Mystic Lake", "Portal"}},
    [0x010201] = {[0] = {"Level Views", "Emerald Passage", "Mystic Lake", "Lake Entrance"}},
    [0x010202] = {[0] = {"Level Views", "Emerald Passage", "Mystic Lake", "Underwater Caverns 1"}},
    [0x010203] = {[0] = {"Level Views", "Emerald Passage", "Mystic Lake", "Underwater Caverns 2"}},
    [0x010204] = {[0] = {"Level Views", "Emerald Passage", "Mystic Lake", "Spring Wario Cavern"}},
    [0x010205] = {[0] = {"Level Views", "Emerald Passage", "Mystic Lake", "Bubbles and Bites"}},
    [0x010206] = {[0] = {"Level Views", "Emerald Passage", "Mystic Lake", "Frog Switch"}},
    [0x010207] = {[0] = {"Level Views", "Emerald Passage", "Mystic Lake", "Escape Path"}},
    [0x010208] = {[0] = {"Level Views", "Emerald Passage", "Mystic Lake", "CD Room"}},
    [0x010209] = {[0] = {"Level Views", "Emerald Passage", "Mystic Lake", "Grab Box Room"}},
    [0x01020A] = {[0] = {"Level Views", "Emerald Passage", "Mystic Lake", "Puzzle Room A"}},
    [0x01020B] = {[0] = {"Level Views", "Emerald Passage", "Mystic Lake", "Puzzle Room B"}},
    [0x010300] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "Portal"}},
    [0x010301] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "Rope Swings 1"}},
    [0x010302] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "Leaf Leap"}},
    [0x010303] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "Health Box"}},
    [0x010304] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "Underground Drop"}},
    [0x010305] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "CD Room"}},
    [0x010306] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "Escape Split Path"}},
    [0x010307] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "Rope Swings 2"}},
    [0x010308] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "Frog Switch"}},
    [0x010309] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "Above Frog Switch"}},
    [0x01030A] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "Underground Escape"}},
    [0x01030B] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "Escape Puzzle Room"}},
    [0x01030C] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "Underground Rolling Escape"}},
    [0x01030D] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "Underground Rolling Escape Exit"}},
    [0x01030E] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "Puzzle Room B"}},
    [0x01030F] = {[0] = {"Level Views", "Emerald Passage", "Monsoon Jungle", "Puzzle Room A"}},
    [0x010400] = {[0] = {"Level Views", "Emerald Passage", "Cractus"}},
    [0x010401] = {[0] = {"Level Views", "Emerald Passage", "Cractus"}},
    [0x020000] = {[0] = {"Level Views", "Ruby Passage", "Curious Factory", "Portal Hallway"}},
    [0x020001] = {[0] = {"Level Views", "Ruby Passage", "Curious Factory", "Unflatten Room"}},
    [0x020002] = {[0] = {"Level Views", "Ruby Passage", "Curious Factory", "Initial Stampers"}},
    [0x020003] = {[0] = {"Level Views", "Ruby Passage", "Curious Factory", "Elevator Climb"}},
    [0x020004] = {[0] = {"Level Views", "Ruby Passage", "Curious Factory", "Conveyor Climb"}},
    [0x020005] = {[0] = {"Level Views", "Ruby Passage", "Curious Factory", "Frog Switch"}},
    [0x020006] = {[0] = {"Level Views", "Ruby Passage", "Curious Factory", "Escape Path"}},
    [0x020007] = {[0] = {"Level Views", "Ruby Passage", "Curious Factory", "Underground Escape"}},
    [0x020008] = {[0] = {"Level Views", "Ruby Passage", "Curious Factory", "Elevator Drop"}},
    [0x020009] = {[0] = {"Level Views", "Ruby Passage", "Curious Factory", "Puzzle Room A"}},
    [0x02000A] = {[0] = {"Level Views", "Ruby Passage", "Curious Factory", "Puzzle Room B"}},
    [0x020100] = {[0] = {"Level Views", "Ruby Passage", "Toxic Landfill", "Portal Room"}},
    [0x020101] = {[0] = {"Level Views", "Ruby Passage", "Toxic Landfill", "Ladders Room"}},
    [0x020102] = {[0] = {"Level Views", "Ruby Passage", "Toxic Landfill", "Above Ladders Room"}},
    [0x020103] = {[0] = {"Level Views", "Ruby Passage", "Toxic Landfill", "Toxic Waters"}},
    [0x020104] = {[0] = {"Level Views", "Ruby Passage", "Toxic Landfill", "Spring Wario Room"}},
    [0x020105] = {[0] = {"Level Views", "Ruby Passage", "Toxic Landfill", "Toxic Currents"}},
    [0x020106] = {[0] = {"Level Views", "Ruby Passage", "Toxic Landfill", "Garbage Blockade"}},
    [0x020107] = {[0] = {"Level Views", "Ruby Passage", "Toxic Landfill", "Transformation Puzzle Room"}},
    [0x020108] = {[0] = {"Level Views", "Ruby Passage", "Toxic Landfill", "Frog Switch"}},
    [0x020109] = {[0] = {"Level Views", "Ruby Passage", "Toxic Landfill", "That One Extra Heart Room That Only Has A Single Heart"}},
    [0x02010A] = {[0] = {"Level Views", "Ruby Passage", "Toxic Landfill", "Below Frog Switch"}},
    [0x02010B] = {[0] = {"Level Views", "Ruby Passage", "Toxic Landfill", "Puzzle Room A"}},
    [0x02010C] = {[0] = {"Level Views", "Ruby Passage", "Toxic Landfill", "Puzzle Room B"}},
    [0x020200] = {[0] = {"Level Views", "Ruby Passage", "40 Below Fridge", "Portal"}},
    [0x020201] = {[0] = {"Level Views", "Ruby Passage", "40 Below Fridge", "Conveyor Climb"}},
    [0x020202] = {[0] = {"Level Views", "Ruby Passage", "40 Below Fridge", "Frog Switch"}},
    [0x020203] = {[0] = {"Level Views", "Ruby Passage", "40 Below Fridge", "Intermission"}},
    [0x020204] = {[0] = {"Level Views", "Ruby Passage", "40 Below Fridge", "Fridge Maze"}},
    [0x020205] = {[0] = {"Level Views", "Ruby Passage", "40 Below Fridge", "Looping Room"}},
    [0x020206] = {[0] = {"Level Views", "Ruby Passage", "40 Below Fridge", "Underground Escape"}},
    [0x020207] = {[0] = {"Level Views", "Ruby Passage", "40 Below Fridge", "Snow And Ice"}},
    [0x020208] = {[0] = {"Level Views", "Ruby Passage", "40 Below Fridge", "Underground Drop"}},
    [0x020209] = {[0] = {"Level Views", "Ruby Passage", "40 Below Fridge", "Puzzle Room A"}},
    [0x02020A] = {[0] = {"Level Views", "Ruby Passage", "40 Below Fridge", "Puzzle Room B"}},
    [0x020300] = {[0] = {"Level Views", "Ruby Passage", "Pinball Zone", "Outside of Pinball Puzzles"}},
    [0x020301] = {[0] = {"Level Views", "Ruby Passage", "Pinball Zone", "Dragon Room"}},
    [0x020302] = {[0] = {"Level Views", "Ruby Passage", "Pinball Zone", "Fruit Room"}},
    [0x020303] = {[0] = {"Level Views", "Ruby Passage", "Pinball Zone", "Jungle Room"}},
    [0x020304] = {[0] = {"Level Views", "Ruby Passage", "Pinball Zone", "Snow Room"}},
    [0x020305] = {[0] = {"Level Views", "Ruby Passage", "Pinball Zone", "Wind-up Room"}},
    [0x020306] = {[0] = {"Level Views", "Ruby Passage", "Pinball Zone", "Space Room"}},
    [0x020307] = {[0] = {"Level Views", "Ruby Passage", "Pinball Zone", "Puzzle Room A"}},
    [0x020308] = {[0] = {"Level Views", "Ruby Passage", "Pinball Zone", "Puzzle Room C"}},
    [0x020309] = {[0] = {"Level Views", "Ruby Passage", "Pinball Zone", "Puzzle Room B"}},
    [0x020400] = {[0] = {"Level Views", "Ruby Passage", "Cuckoo Condor"}},
    [0x020401] = {[0] = {"Level Views", "Ruby Passage", "Cuckoo Condor"}},
    [0x030000] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "Portal"}},
    [0x030001] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "Tower Entrance"}},
    [0x030002] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "Outdoors Side Path"}},
    [0x030003] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "Tower Interior"}},
    [0x030004] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "Tower Basement"}},
    [0x030005] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "Tower Top"}},
    [0x030006] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "Behind The Tower"}},
    [0x030007] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "Fire Wario Puzzles"}},
    [0x030008] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "Keyzer Pipe Room"}},
    [0x030009] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "Hidden Room"}},
    [0x03000A] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "Underground Pipe Exit"}},
    [0x03000B] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "Left of Pipe Exit"}},
    [0x03000C] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "Underground Escape"}},
    [0x03000D] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "CD Room"}},
    [0x03000E] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "Puzzle Room A"}},
    [0x03000F] = {[0] = {"Level Views", "Topaz Passage", "Toy Block Tower", "Puzzle Room B"}},
    [0x030100] = {[0] = {"Level Views", "Topaz Passage", "Big Board", "Portal"}},
    [0x030101] = {[0] = {"Level Views", "Topaz Passage", "Big Board", "Fire Room"}},
    [0x030102] = {[0] = {"Level Views", "Topaz Passage", "Big Board", "Enemy Room"}},
    [0x030103] = {[0] = {"Level Views", "Topaz Passage", "Big Board", "Fat Room"}},
    [0x030104] = {[0] = {"Level Views", "Topaz Passage", "Big Board", "Flat Room"}},
    [0x030105] = {[0] = {"Level Views", "Topaz Passage", "Big Board", "Spring Room"}},
    [0x030106] = {[0] = {"Level Views", "Topaz Passage", "Big Board", "Frog Switch"}},
    [0x030107] = {[0] = {"Level Views", "Topaz Passage", "Big Board", "First Dice"}},
    [0x030108] = {[0] = {"Level Views", "Topaz Passage", "Big Board", "Keyzer Room"}},
    [0x030109] = {[0] = {"Level Views", "Topaz Passage", "Big Board", "Intermediate Room"}},
    [0x03010A] = {[0] = {"Level Views", "Topaz Passage", "Big Board", "Toy Car Room"}},
    [0x03010B] = {[0] = {"Level Views", "Topaz Passage", "Big Board", "Puzzle Room A"}},
    [0x03010C] = {[0] = {"Level Views", "Topaz Passage", "Big Board", "Puzzle Room B"}},
    [0x030200] = {[0] = {"Level Views", "Topaz Passage", "Doodle Woods", "Portal"}},
    [0x030201] = {[0] = {"Level Views", "Topaz Passage", "Doodle Woods", "Hoggus Introduction"}},
    [0x030202] = {[0] = {"Level Views", "Topaz Passage", "Doodle Woods", "Open Area 1"}},
    [0x030203] = {[0] = {"Level Views", "Topaz Passage", "Doodle Woods", "Open Area 2"}},
    [0x030204] = {[0] = {"Level Views", "Topaz Passage", "Doodle Woods", "Orange Room"}},
    [0x030205] = {[0] = {"Level Views", "Topaz Passage", "Doodle Woods", "Blue Room"}},
    [0x030206] = {[0] = {"Level Views", "Topaz Passage", "Doodle Woods", "Grey Square Room"}},
    [0x030207] = {[0] = {"Level Views", "Topaz Passage", "Doodle Woods", "Pink Circle Room"}},
    [0x030208] = {[0] = {"Level Views", "Topaz Passage", "Doodle Woods", "Purple Square Room"}},
    [0x030209] = {[0] = {"Level Views", "Topaz Passage", "Doodle Woods", "Blue Circle Room"}},
    [0x03020A] = {[0] = {"Level Views", "Topaz Passage", "Doodle Woods", "Puzzle Room A"}},
    [0x03020B] = {[0] = {"Level Views", "Topaz Passage", "Doodle Woods", "Puzzle Room B"}},
    [0x030300] = {[0] = {"Level Views", "Topaz Passage", "Domino Row", "Portal"}},
    [0x030301] = {[0] = {"Level Views", "Topaz Passage", "Domino Row", "Race Room"}},
    [0x030302] = {[0] = {"Level Views", "Topaz Passage", "Domino Row", "Spring Room"}},
    [0x030303] = {[0] = {"Level Views", "Topaz Passage", "Domino Row", "Rolling Room"}},
    [0x030304] = {[0] = {"Level Views", "Topaz Passage", "Domino Row", "Swimming Room"}},
    [0x030305] = {[0] = {"Level Views", "Topaz Passage", "Domino Row", "Climbing Room"}},
    [0x030306] = {[0] = {"Level Views", "Topaz Passage", "Domino Row", "Under Portal"}},
    [0x030307] = {[0] = {"Level Views", "Topaz Passage", "Domino Row", "Frog Switch"}},
    [0x030308] = {[0] = {"Level Views", "Topaz Passage", "Domino Row", "Introduction Dominoes"}},
    [0x030309] = {[0] = {"Level Views", "Topaz Passage", "Domino Row", "Jump"}},
    [0x03030A] = {[0] = {"Level Views", "Topaz Passage", "Domino Row", "Puzzle Room A"}},
    [0x03030B] = {[0] = {"Level Views", "Topaz Passage", "Domino Row", "Puzzle Room B"}},
    [0x030400] = {[0] = {"Level Views", "Topaz Passage", "Aerodent"}},
    [0x030401] = {[0] = {"Level Views", "Topaz Passage", "Aerodent"}},
    [0x040000] = {[0] = {"Level Views", "Sapphire Passage", "Crescent Moon Village", "Portal Alleyway"}},
    [0x040001] = {[0] = {"Level Views", "Sapphire Passage", "Crescent Moon Village", "Outdoors 1"}},
    [0x040002] = {[0] = {"Level Views", "Sapphire Passage", "Crescent Moon Village", "Bat Room"}},
    [0x040003] = {[0] = {"Level Views", "Sapphire Passage", "Crescent Moon Village", "Hidden Room"}},
    [0x040004] = {[0] = {"Level Views", "Sapphire Passage", "Crescent Moon Village", "Outdoors 2"}},
    [0x040005] = {[0] = {"Level Views", "Sapphire Passage", "Crescent Moon Village", "Rolling Switch Room"}},
    [0x040006] = {[0] = {"Level Views", "Sapphire Passage", "Crescent Moon Village", "Outdoors 3"}},
    [0x040007] = {[0] = {"Level Views", "Sapphire Passage", "Crescent Moon Village", "Frog Switch"}},
    [0x040008] = {[0] = {"Level Views", "Sapphire Passage", "Crescent Moon Village", "Sewers"}},
    [0x040009] = {[0] = {"Level Views", "Sapphire Passage", "Crescent Moon Village", "Ladder Room"}},
    [0x04000A] = {[0] = {"Level Views", "Sapphire Passage", "Crescent Moon Village", "Sewer Drop"}},
    [0x04000B] = {[0] = {"Level Views", "Sapphire Passage", "Crescent Moon Village", "Puzzle Room A"}},
    [0x04000C] = {[0] = {"Level Views", "Sapphire Passage", "Crescent Moon Village", "Puzzle Room B"}},
    [0x040100] = {[0] = {"Level Views", "Sapphire Passage", "Arabian Night", "Portal"}},
    [0x040101] = {[0] = {"Level Views", "Sapphire Passage", "Arabian Night", "Carpet Entrance"}},
    [0x040102] = {[0] = {"Level Views", "Sapphire Passage", "Arabian Night", "Outdoor Area"}},
    [0x040103] = {[0] = {"Level Views", "Sapphire Passage", "Arabian Night", "Onomi Room"}},
    [0x040104] = {[0] = {"Level Views", "Sapphire Passage", "Arabian Night", "Flying Carpet Room"}},
    [0x040105] = {[0] = {"Level Views", "Sapphire Passage", "Arabian Night", "Flying Carpet Dash Attack Room"}},
    [0x040106] = {[0] = {"Level Views", "Sapphire Passage", "Arabian Night", "Keyzer Room"}},
    [0x040107] = {[0] = {"Level Views", "Sapphire Passage", "Arabian Night", "Frog Switch"}},
    [0x040108] = {[0] = {"Level Views", "Sapphire Passage", "Arabian Night", "Underground Entrance"}},
    [0x040109] = {[0] = {"Level Views", "Sapphire Passage", "Arabian Night", "Underground Exit"}},
    [0x04010A] = {[0] = {"Level Views", "Sapphire Passage", "Arabian Night", "Puzzle Room A"}},
    [0x04010B] = {[0] = {"Level Views", "Sapphire Passage", "Arabian Night", "Puzzle Room B"}},
    [0x040200] = {[0] = {"Level Views", "Sapphire Passage", "Fiery Cavern", "Portal"}},
    [0x040201] = {[0] = {"Level Views", "Sapphire Passage", "Fiery Cavern", "CD Box Room Hot"}},
    [0x040202] = {[0] = {"Level Views", "Sapphire Passage", "Fiery Cavern", "CD Box Room Cold"}},
    [0x040203] = {[0] = {"Level Views", "Sapphire Passage", "Fiery Cavern", "Keyzer Room Hot"}},
    [0x040204] = {[0] = {"Level Views", "Sapphire Passage", "Fiery Cavern", "Keyzer Room Cold"}},
    [0x040205] = {[0] = {"Level Views", "Sapphire Passage", "Fiery Cavern", "Sloped Room Hot"}},
    [0x040206] = {[0] = {"Level Views", "Sapphire Passage", "Fiery Cavern", "Sloped Room Cold"}},
    [0x040207] = {[0] = {"Level Views", "Sapphire Passage", "Fiery Cavern", "Lava Long Jump"}},
    [0x040208] = {[0] = {"Level Views", "Sapphire Passage", "Fiery Cavern", "Frog Switch"}},
    [0x040209] = {[0] = {"Level Views", "Sapphire Passage", "Fiery Cavern", "Room Of Doors"}},
    [0x04020A] = {[0] = {"Level Views", "Sapphire Passage", "Fiery Cavern", "Cavern Entrance Hot"}},
    [0x04020B] = {[0] = {"Level Views", "Sapphire Passage", "Fiery Cavern", "Cavern Entrance Cold"}},
    [0x04020C] = {[0] = {"Level Views", "Sapphire Passage", "Fiery Cavern", "Ice Detour Room"}},
    [0x04020D] = {[0] = {"Level Views", "Sapphire Passage", "Fiery Cavern", "Puzzle Room A"}},
    [0x04020E] = {[0] = {"Level Views", "Sapphire Passage", "Fiery Cavern", "Puzzle Room B"}},
    [0x040300] = {[0] = {"Level Views", "Sapphire Passage", "Hotel Horror", "First Floor"}},
    [0x040301] = {[0] = {"Level Views", "Sapphire Passage", "Hotel Horror", "Second Floor"}},
    [0x040302] = {[0] = {"Level Views", "Sapphire Passage", "Hotel Horror", "Third Floor"}},
    [0x040303] = {[0] = {"Level Views", "Sapphire Passage", "Hotel Horror", "Fourth Floor"}},
    [0x040304] = {[0] = {"Level Views", "Sapphire Passage", "Hotel Horror", "Room 102"}},
    [0x040305] = {[0] = {"Level Views", "Sapphire Passage", "Hotel Horror", "Rooms 103 & 203"}},
    [0x040306] = {[0] = {"Level Views", "Sapphire Passage", "Hotel Horror", "Rooms 104, 204, & 304"}},
    [0x040307] = {[0] = {"Level Views", "Sapphire Passage", "Hotel Horror", "Rooms 303 & 403"}},
    [0x040308] = {[0] = {"Level Views", "Sapphire Passage", "Hotel Horror", "Rooms 201, 202, 301, 302, & 402"}},
    [0x040309] = {[0] = {"Level Views", "Sapphire Passage", "Hotel Horror", "Room 401"}},
    [0x04030A] = {[0] = {"Level Views", "Sapphire Passage", "Hotel Horror", "Room 404"}},
    [0x04030B] = {[0] = {"Level Views", "Sapphire Passage", "Hotel Horror", "Fire Escape"}},
    [0x04030C] = {[0] = {"Level Views", "Sapphire Passage", "Hotel Horror", "Puzzle Room A"}},
    [0x04030D] = {[0] = {"Level Views", "Sapphire Passage", "Hotel Horror", "Puzzle Room B"}},
    [0x040400] = {[0] = {"Level Views", "Sapphire Passage", "Catbat"}},
    [0x040401] = {[0] = {"Level Views", "Sapphire Passage", "Catbat"}},
    [0x050000] = {[0] = {"Level Views", "Entry/Golden Passage", "Golden Passage", "Portal Hallway"}},
    [0x050001] = {[0] = {"Level Views", "Entry/Golden Passage", "Golden Passage", "Underground River"}},
    [0x050002] = {[0] = {"Level Views", "Entry/Golden Passage", "Golden Passage", "Water Current Puzzle"}},
    [0x050003] = {[0] = {"Level Views", "Entry/Golden Passage", "Golden Passage", "Spring Wario Room"}},
    [0x050004] = {[0] = {"Level Views", "Entry/Golden Passage", "Golden Passage", "Danger Room"}},
    [0x050005] = {[0] = {"Level Views", "Entry/Golden Passage", "Golden Passage", "Bat Box Room"}},
    [0x050006] = {[0] = {"Level Views", "Entry/Golden Passage", "Golden Passage", "Keyzer Puzzle Room"}},
    [0x050400] = {[0] = {"Level Views", "Entry/Golden Passage", "Golden Diva"}},
    [0x050401] = {[0] = {"Level Views", "Entry/Golden Passage", "Golden Diva"}},
}